// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eshop.DataAccess.Data;

#nullable disable

namespace eshop.DataAccess.Migrations
{
    [DbContext(typeof(TurkcellDbContext))]
    partial class TurkcellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eshop.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tekstil"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kırtasiye"
                        });
                });

            modelBuilder.Entity("eshop.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CriticalLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "32 GB Ram",
                            DiscountRate = 0.05m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty1131/product/media/images/prod/SPM/PIM/20240112/10/51ae25d2-1655-3ca9-8b5a-3192ff71efac/1_org_zoom.jpg",
                            Name = "Dell XPS 13",
                            Price = 83200m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Tşört işte",
                            DiscountRate = 0.15m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty1131/product/media/images/prod/SPM/PIM/20240112/10/51ae25d2-1655-3ca9-8b5a-3192ff71efac/1_org_zoom.jpg",
                            Name = "Tişört",
                            Price = 200m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Öğrencilerin ihtiyacı",
                            DiscountRate = 0.25m,
                            ImageUrl = "https://cdn.dsmcdn.com/ty1131/product/media/images/prod/SPM/PIM/20240112/10/51ae25d2-1655-3ca9-8b5a-3192ff71efac/1_org_zoom.jpg",
                            Name = "Defter seti",
                            Price = 150m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("eshop.Entities.Product", b =>
                {
                    b.HasOne("eshop.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eshop.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
